// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-vGfNSnSxVdTyNsXULSNmI6FTz15WRXk',
    appId: '1:738832619878:web:6fd64b5ac970f0a47890a7',
    messagingSenderId: '738832619878',
    projectId: 'video-calling-app-dbc82',
    authDomain: 'video-calling-app-dbc82.firebaseapp.com',
    databaseURL: 'https://video-calling-app-dbc82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-calling-app-dbc82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnj0JvIlfpEwAJXyouJme9BKi_hSct2bI',
    appId: '1:738832619878:android:3b1df8a07316c7f47890a7',
    messagingSenderId: '738832619878',
    projectId: 'video-calling-app-dbc82',
    databaseURL: 'https://video-calling-app-dbc82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-calling-app-dbc82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSohGXw_I6BLXlsMGQyK-KErQcloVaRdY',
    appId: '1:738832619878:ios:101cb839f33b2fc57890a7',
    messagingSenderId: '738832619878',
    projectId: 'video-calling-app-dbc82',
    databaseURL: 'https://video-calling-app-dbc82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-calling-app-dbc82.firebasestorage.app',
    iosBundleId: 'com.example.assingment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSohGXw_I6BLXlsMGQyK-KErQcloVaRdY',
    appId: '1:738832619878:ios:101cb839f33b2fc57890a7',
    messagingSenderId: '738832619878',
    projectId: 'video-calling-app-dbc82',
    databaseURL: 'https://video-calling-app-dbc82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-calling-app-dbc82.firebasestorage.app',
    iosBundleId: 'com.example.assingment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-vGfNSnSxVdTyNsXULSNmI6FTz15WRXk',
    appId: '1:738832619878:web:c06925e50e70c79e7890a7',
    messagingSenderId: '738832619878',
    projectId: 'video-calling-app-dbc82',
    authDomain: 'video-calling-app-dbc82.firebaseapp.com',
    databaseURL: 'https://video-calling-app-dbc82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-calling-app-dbc82.firebasestorage.app',
  );
}
